AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for creating AWS services for my portfolio website"

# ----------------------------------------------------------------------
# PARAMETERS
# ----------------------------------------------------------------------
Parameters:
  myLambdacontentS3bucket:
    Type: String
    Description: "Name of the artifact bucket created by the bootstrap stack for Lambda code"

  LambdaCodeKey:
    Type: String
    Default: "dev-lambda.zip"
    Description: "S3 key of Lambda ZIP for the deployment"

  OidcRoleArn:
    Type: String
    Description: "ARN of the OIDC IAM Role used by GitHub Actions for S3 access"

# ----------------------------------------------------------------------
# RESOURCES
# ----------------------------------------------------------------------
Resources:
  # DynamoDB Table
  myDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: submissionId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: submissionId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # SNS Topic for email notification
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: "raseefaz@gmail.com"
          Protocol: email

  # Frontend S3 Bucket (Stable Name)
  myPortfolioContentS3bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "portfolio-dev-myportfoliocontents3bucket-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      WebsiteConfiguration:
        IndexDocument: index.html

  # Frontend Bucket Policy (Website + OIDC)
  myS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref myPortfolioContentS3bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadAccess
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${myPortfolioContentS3bucket}/*"
          - Sid: AllowOidcRoleDeployAccess
            Effect: Allow
            Principal:
              AWS: !Ref OidcRoleArn
            Action:
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource:
              - !Sub "arn:aws:s3:::${myPortfolioContentS3bucket}"
              - !Sub "arn:aws:s3:::${myPortfolioContentS3bucket}/*"

#CloudFront Distribution for Website with HTTPS
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: myPortfolioContentS3bucket
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html

        Origins:
          - Id: S3WebsiteOrigin
            DomainName: !Sub "${myPortfolioContentS3bucket}.s3-website-${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: http-only

        DefaultCacheBehavior:
          TargetOriginId: S3WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6

        PriceClass: PriceClass_100

  # Lambda Execution Role
  myLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: inlineForDynamoDbAndSnsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDBPutItem
                Effect: Allow
                Action: dynamodb:PutItem
                Resource: !GetAtt myDynamoDB.Arn
              - Sid: SNSemail
                Effect: Allow
                Action: sns:Publish
                Resource: !Ref MySNSTopic

  # Lambda Function
  myLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - myLambdaExecutionRole
      - myPortfolioContentS3bucket
    Properties:
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt myLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref myLambdacontentS3bucket
        S3Key: !Ref LambdaCodeKey
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref myDynamoDB
          SNS_TOPIC_ARN: !Ref MySNSTopic
          ALLOWED_ORIGIN: "*"

  myLambdaPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref myLambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*/POST/submit"

  # API Gateway
  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: myApiusingCF
      Description: "API Gateway for contact form submission"

  submitResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: submit

  # POST Method
  myPOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref submitResource
      RestApiId: !Ref RestAPI
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${myLambdaFunction.Arn}/invocations"

  # OPTIONS Method (CORS preflight)
  myOPTIONMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId: !Ref submitResource
      RestApiId: !Ref RestAPI
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true

  # API Deployment + Stage
  myAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestAPI
      Description: !Sub "Deployment - ${AWS::StackName} - ${AWS::Region} - (${AWS::StackId})"

    DependsOn:
      - submitResource
      - myPOSTMethod
      - myOPTIONMethod

  myAPIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestAPI
      DeploymentId: !Ref myAPIDeployment
      StageName: prod

# ----------------------------------------------------------------------
# OUTPUTS
# ----------------------------------------------------------------------
Outputs:
  # WebsiteURL:
  #   Description: "URL of the static portfolio website hosted on S3"
  #   Value: !Sub "http://${myPortfolioContentS3bucket}.s3-website-${AWS::Region}.amazonaws.com"
  #   Export:
  #     Name: !Sub "${AWS::StackName}-WebsiteURL"

  CloudFrontURL:
    Description: "HTTPS URL for portfolio website served via CloudFront"
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontURL"
