name: Deploy a static website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # <<< VERIFY THIS IS YOUR S3 BUCKET'S ACTUAL REGION

      - name: Sync All Website Files (including images) to S3
        # REMOVED: --acl public-read
        run: |
          aws s3 sync ./Projects/Website/ s3://myown-portfolio-website-content-bucket/ \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "node_modules/*" \
            --exclude "package.json" \
            --exclude "package-lock.json"
        env:
          AWS_REGION: us-east-1 # Ensure this matches the above region
