name: Deploy a static website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # <<< IMPORTANT: Double-check this is your S3 bucket's actual region!

      - name: Sync Website Files to S3
        # UPDATED SOURCE PATH: Navigate to the 'website' folder inside 'Projects'
        run: |
          aws s3 sync ./Projects/Website/ s3://myown-portfolio-website-content-bucket / \
            --delete --acl public-read
        env:
          AWS_REGION: us-east-1 # Ensure this matches the above region
