
name: Deploy a static website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # e.g., ap-south-1 for Mumbai

      - name: Sync HTML and CSS to S3
        run: |
          aws s3 sync . s3://my-own-aws-static-website-content-bucket \
            --exclude "*" \
            --include "*.html" \
            --include "*.css" \
            --delete --acl public-read
